//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by codemax.rc
//
#define IDS_PLAYBACK_CANCELED           1
#define IDS_MACRO_ERROR                 2
#define IDS_PROJNAME                    3
#define IDS_MENU_CUT                    4
#define IDS_MENU_COPY                   5
#define IDS_MENU_PASTE                  6
#define IDS_MENU_FIND                   7
#define IDS_MENU_FINDREPLACE            8
#define IDS_MENU_TOGGLEWHITESPACEDISPLAY 9
#define IDS_MENU_UPPERCASESELECTION     10
#define IDS_MENU_LOWERCASESELECTION     11
#define IDS_MENU_TABIFYSELECTION        12
#define IDS_MENU_UNTABIFYSELECTION      13
#define IDS_MENU_UNDO                   14
#define IDS_MENU_REDO                   15
#define IDS_MENU_PROPERTIES             16
#define IDS_MENU_SELFTEST               17
#define IDS_ACTIVEX_WIN_TEXT            18
#define IDS_NUM_KEY                     19
#define IDS_SHIFT                       20
#define IDS_CTRL                        21
#define IDS_ALT                         22
#define IDS_END_RECORDING               23
#define IDS_UNASSIGNED                  24
#define IDS_ERR_HOTKEY_RESERVED         25
#define IDS_ERROR                       26
#define IDS_DELETE_DUPE_MACRO           27
#define IDS_SAVE_MACRO                  28
#define IDS_CURRENTLY_ASSIGNED_TO       29
#define IDS_LINE_TIP_PREFIX             30
#define IDS_DEFAULT                     31
#define IDS_NONE                        32
#define IDS_CURRENTLY_ASSIGNED_TO_CR    33
#define IDS_BINARY                      34
#define IDS_OCTAL                       35
#define IDS_DECIMAL                     36
#define IDS_HEX                         37
#define IDS_CUSTOM                      38
#define IDS_WIN_PROPS                   39
#define IDS_PROP_BOOKMARK               40
#define IDS_PROP_COMMENT                41
#define IDS_PROP_HDIVIDERLINES          42
#define IDS_PROP_VDIVIDERLINES          43
#define IDS_PROP_HIGHLIGHTEDLINE        44
#define IDS_PROP_KEYWORD                45
#define IDS_PROP_LMARGIN                46
#define IDS_PROP_LINENUMBER             47
#define IDS_PROP_NUMBER                 48
#define IDS_PROP_OPERATOR               49
#define IDS_PROP_SCOPEKEYWORD           50
#define IDS_PROP_STRING                 51
#define IDS_PROP_TAGELEMNAME            52
#define IDS_PROP_TAGENT                 53
#define IDS_PROP_TAGATTRNAME            54
#define IDS_PROP_TEXT                   55
#define IDS_PROP_WINDOW                 56
#define IDS_PROP_TAGTEXT                57
#define IDS_FONT_NORMAL                 59
#define IDS_FONT_BOLD                   60
#define IDS_FONT_ITALIC                 61
#define IDS_FONT_BOLDITALIC             62
#define IDS_FONT_UNDERLINE              63
#define IDS_PRINT_JOB_TITLE             64
#define IDS_PAGENUM_OF                  65
#define IDD_GOTO_LINE                   102
#define IDR_HSPLIT                      103
#define IDR_VSPLIT                      104
#define IDR_HVSPLIT                     105
#define IDD_RECORD_MACRO                106
#define IDB_END_MACRO_RECORD            108
#define IDR_RECORD_MACRO                110
#define IDD_SAVE_MACRO                  111
#define IDR_LEFT_MARGIN                 112
#define IDD_FIND                        113
#define IDD_REPLACE                     114
#define IDD_REPEAT_COUNT                115
#define IDD_PROPPAGE_TABS               117
#define IDD_PROPPAGE_KEYBOARD           118
#define IDD_PROPPAGE_COLORFONT          119
#define IDD_PROPPAGE_MISC               120
#define IDR_CEDITX                      121
#define IDR_RANGEX                      123
#define IDR_POSITIONX                   124
#define IDR_LANGUAGEX                   125
#define IDR_GLOBALSX                    126
#define IDR_HOTKEYX                     127
#define IDR_RECTX                       128
#define IDD_ABOUT                       130
#define IDC_URLHAND                     131
#define IDD_ABORTPRINT                  132
#define IDD_WINPROPS                    133
#define IDC_LINENO                      1000
#define IDC_HOTKEY                      1001
#define IDC_MACROS                      1002
#define IDC_HOTKEY_ASSIGNMENT           1003
#define IDC_FIND_TEXT                   1005
#define IDC_WHOLE_WORD                  1006
#define IDC_MATCH_CASE                  1007
#define IDC_MARK_ALL                    1008
#define IDC_PRESERVE_CASE               1008
#define IDC_UP                          1009
#define IDC_DOWN                        1010
#define IDC_REPLACE_TEXT                1011
#define IDC_REPLACE_ALL                 1012
#define IDC_SELECTION                   1013
#define IDC_BUFFER                      1014
#define IDC_REPLACE                     1015
#define IDC_REPEAT_COUNT                1016
#define IDC_COLOR_ITEM                  1017
#define IDC_FORE_COMBO                  1018
#define IDC_BACK_COMBO                  1019
#define IDC_FONT                        1020
#define IDC_PREVIEW                     1021
#define IDC_COMMANDS                    1022
#define IDC_FONT_STYLE                  1022
#define IDC_ASSIGN                      1023
#define IDC_REMOVE                      1024
#define IDC_HOTKEYS                     1026
#define IDC_DESCRIPTION                 1027
#define IDC_SMOOTH_SCROLL               1028
#define IDC_LEFT_MARGIN                 1029
#define IDC_DRAG_DROP                   1030
#define IDC_LINE_TOOLTIP                1031
#define IDC_COLUMN_SEL                  1032
#define IDC_H_SCROLL                    1033
#define IDC_V_SCROLL                    1034
#define IDC_MAX_UNDO                    1035
#define IDC_COLOR_SYNTAX                1036
#define IDC_TAB_SIZE                    1037
#define IDC_H_SPLIT                     1037
#define IDC_EXPAND_TABS                 1038
#define IDC_OFF                         1039
#define IDC_V_SPLIT                     1039
#define IDC_SCOPE                       1040
#define IDC_SEL_BOUNDS                  1040
#define IDC_COPY_PREV                   1041
#define IDC_LANGUAGE                    1042
#define IDC_UNLIMITED                   1043
#define IDC_LIMITED                     1044
#define IDC_BACK_LABEL                  1045
#define IDC_ASSIGNED_TO                 1046
#define IDC_FONT_STYLE_LABEL            1046
#define IDC_RESET                       1047
#define IDOK2                           1049
#define IDC_REG_EXP                     1050
#define IDC_NUMSTYLE                    1050
#define IDC_NUMSTART                    1051
#define IDC_NORM_CASE                   1052
#define IDC_ABOUT_TITLE                 1053
#define IDC_ABOUT_VERSION               1054
#define IDC_ABOUT_URL                   1055
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
